server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  application:
    name: member
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trip
    username: postgres
    password: postgres
  sql:
    init:
      schema-locations: classpath*:db/postgres/schema.sql
      mode: always
      continue-on-error: false
  data:
    redis:
      host: localhost
      port: 6379
      password:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      default.api.timeout.ms: 5000
logging:
  level:
    org.springframework.jdbc.core: TRACE


